# -*- coding: utf-8 -*-
"""final for OSI-FINAL-PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zGK0J15Htin3bOyDZ8Nz9ni03ohSFLP

**Imports and Drive Mounting**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Loading Data**"""

import pandas as pd
import os
def load_data(data_dir):
    label_path = os.path.join(data_dir, 'label.txt')
    tweet_path = os.path.join(data_dir, 'source_tweets.txt')

    labels_df = pd.read_csv(label_path, sep=":", header=None, names=["label", "tweet_id"])
    tweets_df = pd.read_csv(tweet_path, sep="\t", header=None, names=["tweet_id", "text"])

    merged = pd.merge(tweets_df, labels_df, on="tweet_id")
    return merged

"""**Merging Datasets**"""

# Load both datasets
twitter15 = load_data('/content/drive/MyDrive/RumorDetectionDataset/twitter15')
twitter16 = load_data('/content/drive/MyDrive/RumorDetectionDataset/twitter16')

# Combine both
data = pd.concat([twitter15, twitter16]).drop_duplicates().reset_index(drop=True)

"""**Text Cleaning & Label Encoding**"""

import re
import string

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)  # Remove URLs
    text = re.sub(r"@\w+", "", text)     # Remove @mentions
    text = re.sub(r"#", "", text)        # Remove hashtags
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)
    return text.strip()

data["clean_text"] = data["text"].apply(clean_text)

""" **Label Encoding**
**Supervised learning preprocessing step where class names (strings) are mapped to integers.**
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data["label_encoded"] = le.fit_transform(data["label"])
print(le.classes_)  # ['false' 'non-rumor' 'true' 'unverified']

!pip install googletrans==4.0.0-rc1
from googletrans import Translator

from googletrans import Translator
import tqdm

translator = Translator()

# Optional: Detect language
def detect_language(text):
    try:
        return translator.detect(text).lang
    except:
        return 'error'

# Translate function
def translate_to_english(text):
    try:
        result = translator.translate(text, dest='en')
        return result.text
    except:
        return text  # Fallback to original if translation fails

# Apply only if needed (if tweets are not already in English)
# WARNING: This can be slow unless you batch or cache results

print(" Translating tweets to English (if needed)...")
data['translated_text'] = data['text'].apply(translate_to_english)

data['translated_text'] = data['text'].apply(translate_to_english)

# Print some samples before and after translation
for i in range(6):
    print(f"\nOriginal: {data['text'].iloc[i]}")
    print(f"Translated: {data['translated_text'].iloc[i]}")

import numpy as np

# Add fake structure-based context features
np.random.seed(42)
data['is_reply'] = np.random.choice([0, 1], size=len(data), p=[0.8, 0.2])
data['is_retweet'] = np.random.choice([0, 1], size=len(data), p=[0.7, 0.3])

# Merge with text to simulate structural awareness (simple way)
data['text_with_context'] = data.apply(
    lambda row: ("[REPLY] " if row['is_reply'] else "") +
                ("[RETWEET] " if row['is_retweet'] else "") +
                row['translated_text'],
    axis=1
)

texts = data['text_with_context']

# Preview a few processed tweets with reply/retweet context
for i in range(7):
    print(f"\nTweet {i+1}:")
    print(f"Structured Text: {data['text_with_context'].iloc[i]}")

"""**Tokenization and Dataset Preparation for Transformer Models**

OR

**BERT-Compatible Tokenization & Stratified Dataset Splitting**
"""

from transformers import BertTokenizer, TFBertForSequenceClassification, create_optimizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf

# Label encoding
le = LabelEncoder()
data['label_encoded'] = le.fit_transform(data['label'])
labels = data['label_encoded'].values
y_cat = tf.keras.utils.to_categorical(labels, num_classes=4)

# Step 1: Split the RAW text
X_train_texts, X_test_texts, y_train, y_test = train_test_split(
    data['clean_text'].tolist(), y_cat, test_size=0.2, random_state=42, stratify=labels
)

# Step 2: Tokenize AFTER splitting
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

train_enc = tokenizer(X_train_texts, padding=True, truncation=True, max_length=128, return_tensors="tf")
test_enc = tokenizer(X_test_texts, padding=True, truncation=True, max_length=128, return_tensors="tf")

"""**SVM Baseline (TF-IDF)**"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from scipy.sparse import hstack
import numpy as np

# Step 1: Generate or use real metadata
data['verified'] = np.random.choice([0, 1], size=len(data), p=[0.85, 0.15])
data['followers_count'] = np.random.randint(100, 10000, size=len(data))
data['statuses_count'] = np.random.randint(10, 5000, size=len(data))

# Step 2: Split your data
X_text = data['clean_text']
X_meta = data[['verified', 'followers_count', 'statuses_count']]
y = data['label_encoded']

X_train_text, X_test_text, X_train_meta, X_test_meta, y_train_svm, y_test_svm = train_test_split(
    X_text, X_meta, y, test_size=0.2, stratify=y, random_state=42
)

# Step 3: Vectorize the text
vectorizer = TfidfVectorizer(max_features=5000)
X_train_vec = vectorizer.fit_transform(X_train_text)
X_test_vec = vectorizer.transform(X_test_text)

# Step 4: Scale metadata and combine
scaler = StandardScaler()
X_train_meta_scaled = scaler.fit_transform(X_train_meta)
X_test_meta_scaled = scaler.transform(X_test_meta)

X_train_combined = hstack([X_train_vec, X_train_meta_scaled])
X_test_combined = hstack([X_test_vec, X_test_meta_scaled])

# Step 5: Train the SVM model
svm = LinearSVC()
svm.fit(X_train_combined, y_train_svm)
y_pred_svm = svm.predict(X_test_combined)

# Step 6: Evaluate
print("SVM with Metadata Classification Report:")
print(classification_report(y_test_svm, y_pred_svm, target_names=le.classes_))

# --- Logistic Regression ---
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Reuse the TF-IDF vectorized features from SVM section
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_vec, y_train_svm)

# Predict and evaluate
y_pred_log = log_reg.predict(X_test_vec)

print("Logistic Regression Classification Report:")
print(classification_report(y_test_svm, y_pred_log, target_names=le.classes_))

"""**Bi-LSTM Model**-A special RNN that can remember long-term dependencies using gates (input, forget, output) to control information flow."""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf

# Tokenization
tokenizer_dl = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer_dl.fit_on_texts(data['clean_text'])

sequences = tokenizer_dl.texts_to_sequences(data['clean_text'])
padded = pad_sequences(sequences, maxlen=100, padding='post')

# One-hot encode the labels for multi-class classification
y = tf.keras.utils.to_categorical(data['label_encoded'])  # assuming label_encoded has classes 0–3

# Train-test split
X_train_dl, X_test_dl, y_train_dl, y_test_dl = train_test_split(
    padded, y, test_size=0.2, stratify=data['label_encoded'], random_state=42)

# Define model parameters
vocab_size = 10000
embedding_dim = 128
max_length = 100
num_classes = y.shape[1]  # e.g., 4

# Bi-LSTM Model
model_lstm = Sequential()
model_lstm.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length))
model_lstm.add(Bidirectional(LSTM(units=128)))
model_lstm.add(Dropout(0.5))
model_lstm.add(Dense(num_classes, activation='softmax'))  # Multi-class output

# Compile the model
model_lstm.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
#history_lstm = model_lstm.fit(X_train_dl, y_train_dl, epochs=10, validation_split=0.1, batch_size=32)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

history_lstm = model_lstm.fit(
    X_train_dl, y_train_dl,
    epochs=20,  # increased for better learning
    validation_split=0.1,
    batch_size=32,
    callbacks=[early_stop]
)

"""**Generating Classification Report for Model Performance**"""

from sklearn.metrics import classification_report
import numpy as np

y_pred_probs = model_lstm.predict(X_test_dl)
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_true_classes = np.argmax(y_test_dl, axis=1)

print(classification_report(y_true_classes, y_pred_classes))

"""**Training History Visualization: Accuracy and Loss Curves**"""

import matplotlib.pyplot as plt

# plt.scatter(p_valid['targets'],preds, alpha=0.2)
# plt.title('Validation Prediction Result')
# plt.xlabel('Actual')
# plt.ylabel('Prediction')
# plt.show()

plt.plot(history_lstm.history['accuracy'], label='Train Accuracy')
plt.plot(history_lstm.history['val_accuracy'], label='Val Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

plt.plot(history_lstm.history['loss'], label='Train Loss')
plt.plot(history_lstm.history['val_loss'], label='Val Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""**BERT Model Initialization, Optimizer Setup, and Compilation**"""

from transformers import TFBertForSequenceClassification, create_optimizer
from tensorflow.keras.losses import SparseCategoricalCrossentropy
import tensorflow as tf

# 1. Load BERT
bert_model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=4)

# 2. Optimizer (use Hugging Face's create_optimizer)
steps_per_epoch = len(X_train_texts) // 16
total_steps = steps_per_epoch * 6  # For 6 epochs
optimizer, _ = create_optimizer(
    init_lr=2e-5,
    num_train_steps=total_steps,
    num_warmup_steps=0
)

# 3. Compile the model using Hugging Face optimizer and correct loss
bert_model.compile(
    optimizer=optimizer,
    loss=SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

# Convert one-hot to class indices
y_train = np.argmax(y_train, axis=1)
y_test = np.argmax(y_test, axis=1)

print(np.unique(y_train))        # Should now print [0 1 2 3]
print(type(y_train[0]))          # Should be <class 'numpy.int64'> or <class 'int'>

"""**Training the BERT Model on Encoded Text Data**"""

history = bert_model.fit(
    x={
        'input_ids': train_enc['input_ids'],
        'attention_mask': train_enc['attention_mask']
    },
    y=y_train,  # Make sure this is integer encoded (not one-hot)
    validation_data=(
        {
            'input_ids': test_enc['input_ids'],
            'attention_mask': test_enc['attention_mask']
        },
        y_test
    ),
    epochs=6,  # Feel free to increase this for better learning
    batch_size=16,
    verbose=1
)

"""**Plotting BERT Training and Validation Accuracy**"""

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('BERT Training Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""**Evaluating BERT Model with Classification Report**"""

from sklearn.metrics import classification_report
import numpy as np

y_pred_logits = bert_model.predict({
    'input_ids': test_enc['input_ids'],
    'attention_mask': test_enc['attention_mask']
}).logits

y_pred = np.argmax(y_pred_logits, axis=1)  # still needed
y_true = y_test                            # already integer labels

print(classification_report(y_true, y_pred, target_names=le.classes_))

"""**Predicted vs. Actual Labels for Selected Tweets**"""

import random
import pandas as pd

# Map label numbers to string labels
label_map = {0: 'False', 1: 'True', 2: 'Unverified', 3: 'Non-Rumor'}

# This assumes you already did:
# X_train, X_test, y_train, y_test = train_test_split(...)

# Align text data with test split (assuming you split data['clean_text'] or similar)
X = data['text']  # Original tweets
_, X_test_text, _, _ = train_test_split(X, data['label_encoded'], test_size=0.2, stratify=data['label_encoded'], random_state=42)

# Pick a few sample indices from X_test
sample_indices = random.sample(range(len(X_test_text)), 6)

# Print the sample tweets with true and predicted labels
print(" Example Tweet Predictions:\n")
for idx in sample_indices:
    tweet = X_test_text.iloc[idx]
    true_label = label_map[y_test[idx]]
    pred_label = label_map[y_pred[idx]]
    print(f"Tweet: {tweet}")
    print(f"Actual: {true_label}")
    print(f"Predicted: {pred_label}")
    print("-" * 60)

"""**Plotting Confusion Matrix for BERT Model Predictions**"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)
disp.plot(cmap='Blues', xticks_rotation=45)
plt.title("BERT Rumor Classification - Confusion Matrix")
plt.show()

"""**Detailed Visualization of BERT Model Training: Accuracy and Loss Over Epochs**"""

plt.figure(figsize=(10, 4))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("BERT Model Accuracy over Epochs")
plt.legend()
plt.show()

plt.figure(figsize=(10, 4))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("BERT Model Loss over Epochs")
plt.legend()
plt.show()

from transformers import TFBertModel
import tensorflow as tf

# Load the pretrained BERT model (without classifier head)
bert_encoder = TFBertModel.from_pretrained('bert-base-uncased')

# Get embeddings for test set
test_outputs = bert_encoder(
    input_ids=test_enc['input_ids'],
    attention_mask=test_enc['attention_mask']
)

# Extract CLS token embeddings (shape: [num_samples, hidden_size])
cls_embeddings = test_outputs.last_hidden_state[:, 0, :]  # [CLS] token
cls_embeddings_np = cls_embeddings.numpy()

from sklearn.manifold import TSNE
import numpy as np

# Run t-SNE
tsne = TSNE(n_components=2, perplexity=30, random_state=42)
tsne_results = tsne.fit_transform(cls_embeddings_np)

import matplotlib.pyplot as plt

# Make sure y_test is an array of integer labels
import numpy as np
label_names = le.classes_  # from your LabelEncoder

plt.figure(figsize=(10, 6))
for i, label in enumerate(np.unique(y_test)):
    indices = np.where(y_test == label)
    plt.scatter(tsne_results[indices, 0], tsne_results[indices, 1], label=label_names[label], alpha=0.6)

plt.title("t-SNE Visualization of BERT CLS Embeddings")
plt.xlabel("t-SNE Dim 1")
plt.ylabel("t-SNE Dim 2")
plt.legend()
plt.grid(True)
plt.show()

"""**Saving Fine-Tuned BERT Model and Tokenizer**"""

bert_model.save_pretrained("/content/drive/MyDrive/bert_rumor_model")
tokenizer.save_pretrained("/content/drive/MyDrive/bert_rumor_model")